### ISSUE TITLE
explore SparqLight on top of Blazegraph

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/ld4p#10]
Get a sense of 

- [x] find Sparqlight (gregg kellogg, ben ...)
- [x] what would it take to connect SparqLight to Blazegraph 
- [x] what can we do with SparqLight ?

**Comment by darrenleeweber** [comment]
https://github.com/sul-dlss/sparqlight

**Comment by darrenleeweber** [comment]
Sparqlight has some instructions for connecting to blazegraph at
- https://github.com/sul-dlss/sparqlight#running-on-blazegraph

**Comment by dazza-codes** [comment]
I got the `develop` branch of sparqlite working against my laptop instance of blazegraph.  The README did not work for me out-of-the-box.  I had to first create a new namespace and chose `sparqlite` (with all the defaults for a 'triples' store).  Then run `bundle exec rake secrets` and add that to the `config/secrets.yml` for the `PRODUCTION` environment and then the following worked:
```
export SPARQL_URL=http://localhost:9999/blazegraph/namespace/sparqlite/sparql
RAILS_ENV=production bundle exec rake db:migrate
RAILS_ENV=production bundle exec rake db:seed
RAILS_ENV=production bundle exec rails server
```
Then open http://localhost:3000/

Out of the box, it _seems_ to do nothing at all.  It just provides instructions about getting things moving for a vanilla blacklight.

**Comment by jgreben** [comment]
Sparqlight pretty much connects to blazegraph OOTB, but we would need to do some work to get it to query and index the Bibframe data in our instance of blazegraph. There is a  controller in Sparqlight that is set  up to query a specific example dataset according to that data's ontology. We would need to abstract that controller to work with datasets of differing ontologies (or at least change it to work with BF2). It is unknown how performant the app will be when dealing with a much larger set of records.

**Comment by dazza-codes** [comment]
Closing this, as we have explored it and discussed the concerns about using it.  If we need additional work, it will be in new tickets for specific details (perhaps those details will be issues on the sparlite repo itself).
