### ISSUE TITLE
Does LoC bf2 create authorities as Real World Objects

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/ld4p#14]
That is, not fake URIs ...

If the answer is no, then we will need to create ticket(s) to add a (standalone) processing step to transform our own authority URIs (from Symphony lookup) to RWO.

**Comment by jgreben** [comment]
Example of how the new BF2 converter handles a bf:Agent:
```
<bf:Agent rdf:about="http://example.org/cis26015102#Agent100-17">
            <rdf:type rdf:resource="http://id.loc.gov/ontologies/bibframe/Person"/>
            <bflc:name00MatchKey>Doerr, Anthony, 1973-</bflc:name00MatchKey>
            <bflc:primaryContributorName00MatchKey>Doerr, Anthony, 1973-</bflc:primaryContributorName00MatchKey>
            <bflc:name00MarcKey>1001 $aDoerr, Anthony,$d1973-$eauthor.$0http://id.loc.gov/authorities/names/n2001038314$0http://viaf.org/viaf/79550093$0http://isni.org/isni/0000000114758160</bflc:name00MarcKey>
            <rdfs:label>Doerr, Anthony, 1973-</rdfs:label>
            <bf:identifiedBy>
              <bf:Identifier>
                <rdf:value>http://id.loc.gov/authorities/names/n2001038314</rdf:value>
              </bf:Identifier>
            </bf:identifiedBy>
            <bf:identifiedBy>
              <bf:Identifier>
                <rdf:value>http://viaf.org/viaf/79550093</rdf:value>
              </bf:Identifier>
            </bf:identifiedBy>
            <bf:identifiedBy>
              <bf:Identifier>
                <rdf:value>http://isni.org/isni/0000000114758160</rdf:value>
              </bf:Identifier>
            </bf:identifiedBy>
</bf:Agent>
```

The new converter currently constructs a tentative URI, and ultimately the conversion will construct a RWO URI for this person, but that part of the conversion isn’t ready yet, but it is their intent to create a URI to the RWO, not to the authority record. If we start using this new converter as-is, we may still need to do some URI rewriting of the `bf:Identifier`

**Comment by jgreben** [comment]
According to the `bibframe.rdf` ontology:
```
<owl:Class rdf:about="http://id.loc.gov/ontologies/bibframe/Identifier">
    <rdfs:label>Identifier</rdfs:label>
    <rdfs:subClassOf rdf:resource="http://www.w3.org/2000/01/rdf-schema#Resource"/>
    <skos:definition>Token or name that is associated with a resource, such as a URI or an ISBN.</skos:definition>
    <dcterms:modified>2016-04-21 (New)</dcterms:modified>
  </owl:Class>
```

**Comment by darrenleeweber** [comment]
While looking at https://github.com/sul-dlss/ld4p/issues/25 (does the BF2 converter use our MarcXML OK), I started to wonder —  can we confirm whether the BF2 ontology requires these authority URIs to be a RWO or not?  And, if it must be a RWO, do we already have URIs in the correct form for RWO? (i.e. are the VIAF URIs in the correct form for a RWO?  I think VIAF use a trailing slash to differentiate between RWO and not.  Also, our authority URI providers may not be aware of or required to consider this issue.)

**Comment by darrenleeweber** [comment]
Consider whether a bf:Person must be bf:identifiedBy a URI that is a RWO?  My first guess is that they have not placed any range constraints on the bf:identifiedBy other than the generic bf:Identifier.  If so, as noted above, this entity is a generic identifier that could be any kind of identifier (RWO or not).

**Comment by darrenleeweber** [comment]
A `bf:Agent' is a subclass of `foaf:Agent`, so now the question is whether a `foaf:Agent` is a RWO?

**Comment by darrenleeweber** [comment]
http://xmlns.com/foaf/spec/#term_Agent is not concerned about a distinction between RWO and a catalog record.  So I can't be sure yet whether a bf:Agent is a RWO or not.

**Comment by jgreben** [comment]
The answer to the question is "No." Currently the LoC BF2 converter does not create authorities as RWOs.
