### ISSUE TITLE
create marcxml-to-bf2 git repo

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/ld4p#17]
like ld4p-marcxml-to-bibframe1, the goal is to 

- have a working test script that can convert a test marcxml file into a test rdfxml file containing the results of running the marc2bibframe2 converter.  
- can deploy to converter box with capistrano
- can run test script with capistrano

**Comment by darrenleeweber** [comment]
There is now a new repo for this.  It was created by first using github to create a new repo and then following their guidelines on how to populate it with an existing repo (using our bf1 repo to start with).  The details on a laptop look like this:

```
$ git clone git@github.com:sul-dlss/ld4p-marcxml-to-bibframe1.git
Cloning into 'ld4p-marcxml-to-bibframe1'...
$ git clone git@github.com:sul-dlss/ld4p-marcxml-to-bibframe1.git ld4p-marcxml-to-bibframe2
Cloning into 'ld4p-marcxml-to-bibframe2'...
$ cd ld4p-marcxml-to-bibframe2/
$ git remote -v
origin	git@github.com:sul-dlss/ld4p-marcxml-to-bibframe1.git (fetch)
origin	git@github.com:sul-dlss/ld4p-marcxml-to-bibframe1.git (push)
$ git remote rm origin
$ git remote -v
$ git remote add origin git@github.com:sul-dlss/ld4p-marcxml-to-bibframe2.git
$ git push -u origin master
Counting objects: 1059, done.
Delta compression using up to 2 threads.
Compressing objects: 100% (504/504), done.
Writing objects: 100% (1059/1059), 33.54 MiB | 761.00 KiB/s, done.
Total 1059 (delta 459), reused 1059 (delta 459)
remote: Resolving deltas: 100% (459/459), done.
To git@github.com:sul-dlss/ld4p-marcxml-to-bibframe2.git
 * [new branch]      master -> master
Branch master set up to track remote branch master from origin.
```

So, effectively, this copies over all the bf1 repo to the new bf2 repo as the starting point.  We could now split out the additional setup into separate issues to be tackled by any team members.

**Comment by darrenleeweber** [comment]
The PR in https://github.com/sul-dlss/ld4p-marcxml-to-bibframe2/issues/2 resolves each of the items noted, i.e.
- [x] have a working test script that can convert a test marcxml file into a test rdfxml file containing the results of running the marc2bibframe2 converter.  
- [x] can deploy to converter box with capistrano
- [x] can run test script with capistrano
