### ISSUE TITLE
index marc into sul-solr searchworks-rdf-dev

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/ld4p#19]
We need to know if we can point solrmarc-sw at the Solr 6 index in sul-solr and have the marc data be indexed cleanly (or close to cleanly).   

This is because we will need a combined index of all marc data from Symphony with casalini data indexed from blazegraph.

**Comment by ndushay** [comment]
- this should be accomplished by changing `solr.url` type properties in `sw_config.properties`
- you may need to talk to devops folks for sw-solr-g (?) to have access to http://sul-solr.stanford.edu/solr/searchworks-rdf-dev

**Comment by shelleydoljack** [comment]
1 MARC file from the recent full dump indexed into sul-solr/searchworks-rdf-dev collection, total 386,705 documents:
https://sul-solr.stanford.edu/solr/searchworks-rdf-dev/select?fq=collection:sirsi&indent=on&q=*:*&wt=json

There were two records that didn't get indexed with an "Async exception during distributed update" error in the log.
