### ISSUE TITLE
load BF2 casalini data into blazegraph

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/ld4p#21]

**Comment by dlrueda** [comment]
Why is this blocked?  What is blocking it?

**Comment by dazza-codes** [comment]
The BG-dev box was able to load all new BF2 RDF data, so various discovery work can use it.  There are now 59,952 `bf:Work` in the triple store.

Go to http://sul-ld4p-blazegraph-dev.stanford.edu/blazegraph/#query to explore the data.  For example, issue a query to get all the works, i.e.
```sparql
PREFIX bf: <http://id.loc.gov/ontologies/bibframe/>
SELECT ?s WHERE { ?s a bf:Work . }
```
