### ISSUE TITLE
remove BF1 data on remote VMs and blazegraph

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/ld4p#22]
for blazegraph:
- [x] drop namespace and recreate it

for rdf files:
- [x] remove them from /rdf shared dir
- [ ] remove them from ~/data/dw/marcrdf  dir or wherere it is

**Comment by darrenleeweber** [comment]
The `ld4p` namespace was dropped and recreated with these properties (these are provided by the default 'triples' mode):
```
com.bigdata.rdf.sail.isolatableIndices=false
com.bigdata.rdf.store.AbstractTripleStore.justify=false
com.bigdata.rdf.sail.namespace=ld4p
com.bigdata.rdf.store.AbstractTripleStore.axiomsClass=com.bigdata.rdf.axioms.NoAxioms
com.bigdata.rdf.sail.truthMaintenance=false
com.bigdata.namespace.ld4p.lex.com.bigdata.btree.BTree.branchingFactor=400
com.bigdata.rdf.store.AbstractTripleStore.textIndex=false
com.bigdata.rdf.store.AbstractTripleStore.vocabularyClass=com.bigdata.rdf.vocab.core.BigdataCoreVocabulary_v20160317
com.bigdata.rdf.store.AbstractTripleStore.quads=false
com.bigdata.rdf.store.AbstractTripleStore.statementIdentifiers=false
com.bigdata.rdf.store.AbstractTripleStore.geoSpatial=false
com.bigdata.namespace.ld4p.spo.com.bigdata.btree.BTree.branchingFactor=1024
```

When creating a 'triples' mode KB, there are options that can be toggled; all of these were left in their default state (not enabled), i.e.

- [ ] Inference
- [ ] Isolatable indices
- [ ] Full text index
- [ ] Enable geospatial

**Comment by darrenleeweber** [comment]
Data were removed from /rdf, i.e.
```
[ld4p@sul-ld4p-blazegraph-dev ~]$ find /rdf/MarcRDF/ -type f -name '*.rdf' | wc -l
36074
[ld4p@sul-ld4p-blazegraph-dev ~]$ find /rdf/MarcRDF/ -type f -name '*.rdf' -exec rm {} \;
[ld4p@sul-ld4p-blazegraph-dev ~]$ find /rdf/MarcRDF/ -type f -name '*.rdf' | wc -l
0
[ld4p@sul-ld4p-blazegraph-dev ~]$ ls -l /rdf/MarcRDF/
total 0
```

The data in the test directory was left alone, assuming it is part of some "integration" or deployment test scripts, i.e.
```
[ld4p@sul-ld4p-blazegraph-dev ~]$ ls -l /rdf/test/
total 16
-rw-rw-r-- 1 ld4p ld4p 13075 Feb 27 14:00 one_record.rdf
```

**Comment by darrenleeweber** [comment]
Could not find any RDF data outside the /rdf directory, there is no `~/data/` path on the blazegraph-dev box.  (Might be confused with the converter-dev box?)
