### ISSUE TITLE
Convert single record for review then post to triplestore [create RoR app]

### ISSUE THREAD

**Issue by dlrueda** [sul-dlss/ld4p#32]
Convert a single record to RDF to get the data into the linked-data ILS/discovery environment. Should be self-service for Tech Service librarians, or automated by Systems staff.

**Comment by dlrueda** [comment]
Convert a single record to RDF to get the data into the linked-data ILS/discovery environment. Should be self-service for Tech Service librarians, or automated by Systems staff.

**Comment by dlrueda** [comment]
Josh has current code for a web interface that takes ckey as input, accesses Symphony to dump marc, convert to marcxml, and convert to RDF BF1.  Need to get this working with BF2.

Should decide how can be integrated into current code.  I'd rather NOT just update current code to BF2, wold much rather make it part of what we're doing in the sprint.

For discussion for next sprint.

**Comment by jgreben** [comment]
At this point we will not do the post to triplestore part because this would involve reconcilation, and that part has not been worked out yet. For now we will just use the code that exists to display BF2.

**Comment by jgreben** [comment]
`ld4p-marc21-to-xml` needs to be able to accept an on-the-fly conversion of a single or batch or records.

**Comment by jgreben** [comment]
The decision today is to start creating a RoR app to replace the "ckey2bibframe" app that is currently on bodoni. Then we will need to decide how to tap it into the coponent repos for record conversion.

**Comment by jgreben** [comment]
Also see questions #34 and https://github.com/sul-dlss/ld4p-marc21-to-xml/issues/25

**Comment by jgreben** [comment]
Need Java 8 installed on `libsys-webforms-(dev stage prod)`in order for the converter to work on those boxes. I created an issue: https://github.com/sul-dlss/operations-tasks/issues/356

**Comment by eefahy** [comment]
Why use the libsys-webforms machines for this? Does it already have a part to play in the ld4p stuff?

**Comment by jgreben** [comment]
https://github.com/sul-dlss/libsys-webforms/pull/388
