### ISSUE TITLE
Investigate BF2->solr mapping

### ISSUE THREAD

**Issue by dlrueda** [sul-dlss/ld4p#36]
Use the LD4L1 code as a starting point.

LD4L code is under https://github.com/ld4l/ld4l_browser_data/tree/master/lib/ld4l_browser_data/indexing

Consult Vitus in MD, and whomever else he proposes.

**Comment by shelleydoljack** [comment]
Working document for gryphon-search and others to contribute: 
https://consul.stanford.edu/display/LD4P/Bibframe+2.0+to+Solr+Mapping

**Comment by ndushay** [comment]
This sprung up while I was away.  I think our priority SW "concepts" are documented here https://consul.stanford.edu/display/DLSSDOCS/Minimum+Requirements+for+Non-MARC+Descriptive+Metadata+in+SearchWorks

with some possibly irrelevant addl information here https://github.com/ld4l-labs/marc2rdf-validator/issues/25

**Comment by shelleydoljack** [comment]
There's also this document on required solr fields:
https://consul.stanford.edu/display/NGDE/Required+and+Recommended+Solr+Fields+for+SearchWorks+documents
