### ISSUE TITLE
pick ~20 BF2 instances to seed our indexing code

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/ld4p#48]
- want a sorting title diff from full title
- want records with 700at if there are any  (for addl authors (?))
- want records with diff 008 byte 6 and 7 values (for diff formats)

send some sample RDFXML to Shelley, along with corresponding marcxml

**Comment by shelleydoljack** [comment]
Ok, I've gone through the casalini marc records and I think we should index these into the solr instance (ckeys listed by resource type):

Serials:
8596214
10947648
11624640
11682224

Sound recordings:
7907729
9144273  (has 700 $a and $t)
10586419

Maps:
6828286
2650945
10785585
11743826

Scores:
7164326
7164327
11651132

Computer file:
8830687

Visual material:
10415691
2911666

Books:
6828305
5417803
6828266
7378541
7378540
7515282
10415000
10415005

Records with 700 $a and $t:
5598090
6960263
6984973
7201787
9214945
11886335

**Comment by ndushay** [comment]
We need to have examples of multiple bf:Instances for a single bf:Work, and multiple bf:Works for a single bf:Instance, too.

**Comment by shelleydoljack** [comment]
I think these ckeys might have the examples you're looking for.
Ckeys with possible multiple works for a single instance:
11610596 (has linked 880 fields)
10333099
11756782
8089220
9144273

Ckeys with possible multiple instances for a single work. So far I could only find an example with the work in a subject heading. These ckeys all have: 600  00$aDante Alighieri,$d1265-1321.$tDivina commedia.
6836222
6841786
7641541
7831232
11520496
11843443

**Comment by shelleydoljack** [comment]
Ckeys of RDA book records:
8801141
9633237
10083913
10249086
11111570
