### ISSUE TITLE
ensure the ckey is in the casalini records we convert

### ISSUE THREAD

**Issue by shelleydoljack** [sul-dlss/ld4p#51]
Naomi and I are noticing that the records on the converter box in ld4p/data/marc_xml do not have the ckey in the 001 field. It looks like some have the Casalini record number (it_1234) or the ocn number. Since we want to use the ckey as the instance identifier in bibframe, we need to make sure the catalogdump flag is putting the ckey in the 001 field and the other 001's are removed.

**Comment by jgreben** [comment]
We did a re-dump of the casalini marc records using a similar set of command flags that we use for Searchworks. This dump includes the ckey as the 001 without the `it xxx` or `ocm xxx` and the files are now on the converter-dev box.

 ```[ld4p@sul-ld4p-converter-dev marc]$ ll
total 62880
-rw-rw-r-- 1 ld4p ld4p 20549482 Mar 14 13:08 casalini0.mrc
-rw-rw-r-- 1 ld4p ld4p 21027038 Mar 14 13:08 casalini1.mrc
-rw-rw-r-- 1 ld4p ld4p 22400373 Mar 14 13:08 casalini2.mrc
-rw-rw-r-- 1 ld4p ld4p    96048 Mar 14 13:07 casalini_keys0
-rw-rw-r-- 1 ld4p ld4p   101435 Mar 14 13:07 casalini_keys1
-rw-rw-r-- 1 ld4p ld4p   108738 Mar 14 13:07 casalini_keys2
drwxrwxr-x 2 ld4p ld4p     4096 Mar 14 13:08 old
```
The `old` files could/should be moved to `../marc_archive` or maybe we don’t care about those anymore and we can delete them?

The catalogdump command we are using now is `/s/sirsi/Unicorn/Bin/catalogdump -om -kc -h -z -j -n dumpjunktag.Bibframe 2>/dev/null`

This will be recorded on a Consul page. it’s also in a settings file in `libsys-webforms` and so will end up in `shared_configs` as such
