### ISSUE TITLE
create  github issues and email Ray for concerns with LC BF2 converter (?)

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/ld4p#57]
The idea is to create a ? google chart ? where developers and metadata folks can describe concerns with the LC BF2 converter (with examples, when possible) and give LC access to this document in progress.

confer with Arcadia and Michelle about this ...

**Comment by ndushay** [comment]
latest (from email and converter call:  put github issue in lcnetdev/marc2bibframe2 and also email Ray with the link to the issue and the text of the issue.

**Comment by dazza-codes** [comment]
- https://github.com/lcnetdev/marc2bibframe2/issues/11
