### ISSUE TITLE
Filter out only book records from Casalini ckeys and catalogdump

### ISSUE THREAD

**Issue by shelleydoljack** [sul-dlss/ld4p#60]

**Comment by shelleydoljack** [comment]
Actually, there are only 27 records that are not book records. These are the ckeys of the not book records:
2650945
2911666
2911781
2912857
2914708
6828286
7164326
7164327
7907729
8596214
8830687
9144273
9347773
10415691
10576418
10578389
10586419
10727639
10785585
10947648
11624628
11624640
11651132
11682224
11743826
11874840
15007992

**Comment by ndushay** [comment]
closing in favor of sul-dlss/sparql_to_sw_solr#10
