### ISSUE TITLE
Document Solr and Stanford::Mods normalization methods

### ISSUE THREAD

**Issue by jgreben** [sul-dlss/ld4p#76]
Document of provide a link to an existing document about how Solr intrinsically handles some punctuation, and also about what `stanford-mods` provides for us in terms of normalization.

**Comment by ndushay** [comment]
Sadly the documentation is in the stanford-mods code.  :-P

**Comment by ndushay** [comment]
Given the new consul document about SearchWorks indexing:  https://consul.stanford.edu/pages/viewpage.action?pageId=156860714  

Can we close this?

**Comment by jgreben** [comment]
👍 I added a link to the schema.xml file and an additional bullet point.
```
- Look it up in Solr schema.xml.  How the Solr field processes the raw text at index time informs the minimum processing for the field value being sent to Solr.
-- Here you will find how a particular data field is modified/normalized for Solr indexing purposes.
-- is it single valued or multi-valued?
-- how is it modified by Solr processing?
--- tokenized, etc.
```

**Comment by ndushay** [comment]
cool!   Does that mean we can close this issue?  I also added more info on where to look for code in solrmarc-sw.

**Comment by jgreben** [comment]
I think yes!

Josh

On Apr 19, 2017, at 4:31 PM, Naomi Dushay <notifications@github.com<mailto:notifications@github.com>> wrote:


cool! Does that mean we can close this issue? I also added more info on where to look for code in solrmarc-sw.
