### ISSUE TITLE
update bf2 converter code and rerun marcxml -> bg

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/ld4p#78]
The LC converter code has been updated since we ran our marcxml thru it.  In particular, Arcadia notes "I checked the data currently in blazegraph and it is the older version without the madsrdf:componentList node that separates out the parts of the subject.  this affects the solr mappings for topic_search and topic_facet."  (see #48)

So:

- [x] update converter code in shared directory for marcxml-to-rdf deployed repo
- [x] archive the existing RDF data
- [x] reconvert our marcxml to rdf
- [x] update rdf in bg, using a different namespace
  - Note that Daniel loaded marc languages and relator terms into that bg namespace;  you may need to ask him to reload those (should be no big deal).

**Comment by ndushay** [comment]
Reconvert everything;  retain old rdf files (in case we need to reload bg with old data);  add new rdf in different namespace.

Note:  not indexing new data into Solr as part of this issue.  Also, waiting for Naomi to return.

**Comment by dazza-codes** [comment]
- [x] updated converter code on converter-dev box, using capistrano, i.e.
```
$ bundle exec cap dev loc:update_marc2bibframe2
Pseudo-terminal will not be allocated because stdin is not a terminal.
00:00 loc:clone_marc2bibframe2
      01 cd /opt/app/ld4p/ld4p-marcxml-to-bibframe2/shared && if [ ! -d loc_marc2bibframe2 ]; then   git clone https://github.com…
    ✔ 01 ld4p@sul-ld4p-converter-dev.stanford.edu 1.021s
00:01 loc:update_marc2bibframe2
      01 cd /opt/app/ld4p/ld4p-marcxml-to-bibframe2/shared/loc_marc2bibframe2 && git pull origin master
      01 From https://github.com/lcnetdev/marc2bibframe2
      01  * branch            master     -> FETCH_HEAD
      01 Updating d0d2296..2fcfa46
      01 Fast-forward
      ... snipped details ...
      01  xsl/marc2bibframe2.xsl                            |  11 +-
      01  xsl/utils.xsl                                     |  23 ++
      01  73 files changed, 961 insertions(+), 333 deletions(-)
    ✔ 01 ld4p@sul-ld4p-converter-dev.stanford.edu 2.054s
Pseudo-terminal will not be allocated because stdin is not a terminal.
```

**Comment by dazza-codes** [comment]
- [x] archived the existing RDF data, i.e.
```
[ld4p@sul-ld4p-converter-dev ~]$ rm /rdf/marc_rdf_archive/*.rdf
[ld4p@sul-ld4p-converter-dev ~]$ mv /rdf/marc_rdf/*.rdf /rdf/marc_rdf_archive/
```

**Comment by dazza-codes** [comment]
- [x] reconvert our marcxml to rdf, i.e. replaced data in `/rdf/marc_rdf/`
```
[ld4p@sul-ld4p-converter-dev ~]$ ./ld4p-marcxml-to-bibframe2/current/bin/marcxml_to_bf2_batch.sh
Conversion logs to /opt/app/ld4p/ld4p-marcxml-to-bibframe2/releases/20170308221435/log/marcxml_to_bf2_20170414T133952.log
Searching MARC-XML files: /opt/app/ld4p/data/marc_xml/*.xml
```

**Comment by dazza-codes** [comment]
- [x] Loading updated RDF into http://sul-ld4p-blazegraph-dev.stanford.edu/blazegraph/namespace/bibframe2_201704/sparql
  - the new Blazegraph namespace `bibframe2_201704` has inference enabled

**Comment by dazza-codes** [comment]
Created new issue to load additional data, https://github.com/sul-dlss/ld4p/issues/81
