### ISSUE TITLE
sparqlight - report on its state (possibly at partners mtg)

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/ld4p#79]
- what it is
- what it was meant to do
- what we tried to do
- demo of it (w/ baked in coin data) - for non-developers
- here's what's needed to make it more generally useful ...

(5-10 min discussion with LD4P partners on thurs)

**Comment by ndushay** [comment]
document "here's what is needed to make it more generally useful" for two audiences:

1.  Tom  (non-developer managers assessing it)
2.  developer wanting to use it

**Comment by dazza-codes** [comment]
Adding documentation to https://github.com/sul-dlss/sparqlight/wiki/Sparqlight

**Comment by dazza-codes** [comment]
Sparqlite using Bibframe 2 is working, in preliminary form in the `bibframe2` branch, i.e.
- https://github.com/sul-dlss/sparqlight/tree/bibframe2
